name: Deploy With Docker to AWS Server
on:
  push:
    branches:
      - main #main commit and push = [main,master]
jobs:
  deploy:
    # Github Actions가 제공하는 Ubuntu 환경
    runs-on: ubuntu-latest
    # 실행순서 지정
    # name = stage = step
    steps:
     # 어떤 소스를 가지고올지 => src /build.gradle gradlew Dockerfile
     #코드 체크 (Repository)
     - name: Checkout:repository
       uses: actions/checkout@v4
     #JDK 설정 => Spring-Boot 프로젝트 build => jdk 설정
     - name: SetUp JDK 21
       uses: actions/setup-java@v4
       with:
         distribution: 'temurin'
         java-version: '21'
     # 환경 설정
     # Gradlew 권한 부여 
     - name: Set gradlew permission
       run: |
         chmod +x ./gradlew
     # Gradle Build 
     - name: Build with Gradlew
       run: ./gradlew clean build -x test
     # Docker Hub 연결 - 로그인
     - name: Login to DockerHub
       run: |
         echo "${{secrets.DOCKER_PASSWORD}}" |\
         docker login \
         -u "${{secrets.DOCKER_NAME}}" \
         --password-stdin
     # Docker 이미지 생성
     - name: Build Docker Image
       run: |
         docker build \
         -t ${{secrets.DOCKER_NAME}}/last-app:latest .
     # Docker Hub 업로드
     - name: Push Docker Image
       run: |
         docker push \
         ${{secrets.DOCKER_NAME}}/last-app:latest
     # AWS 연결 
     - name: Set SSH key Permission
       run: |
         mkdir -p ~/.ssh
         echo "${{secrets.SERVER_SSH_KEY}}" > ~/.ssh/id_ed25519
         chmod 600 ~/.ssh/id_ed25519
     # ADD SSH Key 
     - name: Add SSH Key 
       uses: webfactory/ssh-agent@v0.5.3
       with:
         ssh-private-key: ${{secrets.SERVER_SSH_KEY}}
     # Add Known_hosts (AWS IP주소)
     - name: Add Known_hosts
       run: |
         ssh-keyscan -H 3.39.226.126 >> ~/.ssh/known_hosts
     # DB관련 => .env
     - name: Set Environment
       run: |
         ssh ubuntu@3.39.226.126 << EOF
         mkdir -p ~/app
         cd ~/app
         rm -f .env
         touch .env
         echo "COMMDB_URL=${{secrets.DB_URL}}" >> ~/app/.env
         echo "DB_USERNAME=${{secrets.DB_USERNAME}}" >> ~/app/.env
         echo "DB_USERPASSWORDE=${{secrets.DB_USERPASSWORD}}" >> ~/app/.env
         chmod 600 ~/app/.env
         EOF
     # Docker Hub 이미지 Pull
     - name: Deploy DockerHub Image on Server
       run: |
         ssh ubuntu@3.39.226.126 << 'EOF'
         docker stop last-app ||true
         docker rm last-app ||true
         docker pull ${{secrets.DOCKER_NAME}}/last-app:latest
         docker run -d --name last-app -p 9090:9090 --env-file ~/app/.env ${{secrets.DOCKER_NAME}}/last-app:latest
         EOF
